/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso.fatec.boundary;

import java.time.LocalDate;

import edu.curso.fatec.control.AlunoControl;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class AlunoBoundary extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    TextField raFT = new TextField();
    TextField nomeTF = new TextField();
    TextField idadeTF = new TextField();
    TextField nascimentoTF = new TextField();

    @Override
    public void start(Stage stage) {
        VBox painel = new VBox();

        GridPane entradas = new GridPane();

        Label raL = new Label("Ra:");
        entradas.add(raL, 0, 0);
        // TextFild
        entradas.add(raFT, 1, 0);

        Label nomeL = new Label("Nome:");
        entradas.add(nomeL, 0, 1);
        // TextFild
        entradas.add(nomeTF, 1, 1);

        Label idadeL = new Label("Idade:");
        entradas.add(idadeL, 0, 2);
        // TextFild
        entradas.add(idadeTF, 1, 2);

        Label nascimentoL = new Label("Nascimento:");
        entradas.add(nascimentoL, 0, 3);
        // TextFild
        entradas.add(nascimentoTF, 1, 3);

        // botoes
        Button inserir = new Button("Inserir");
        entradas.add(inserir, 0, 4);
        Button atualizar = new Button("Atualizar");
        entradas.add(atualizar, 1, 4);
        Button remover = new Button("Remover");
        entradas.add(remover, 2, 4);
        Button pesquisar = new Button("Pesquisar");
        entradas.add(pesquisar, 3, 4);

        entradas.setHgap(5);
        entradas.setVgap(5);

        TableView cadastros = new TableView<>();

        TableColumn column1 = new TableColumn<>("Ra");
        TableColumn column2 = new TableColumn<>("Nome");
        TableColumn column3 = new TableColumn<>("Idade");
        TableColumn column4 = new TableColumn<>("Nascimento");

        column1.setCellValueFactory(new PropertyValueFactory<>("ra"));
        column2.setCellValueFactory(new PropertyValueFactory<>("nome"));
        column3.setCellValueFactory(new PropertyValueFactory<>("idade"));
        column4.setCellValueFactory(new PropertyValueFactory<>("nascimento"));

        cadastros.getColumns().add(column1);
        cadastros.getColumns().add(column2);
        cadastros.getColumns().add(column3);
        cadastros.getColumns().add(column4);

        AlunoControl ac = new AlunoControl();
        // conecoes do observer

        cadastros.setItems(ac.getAlunos());
        ac.atualizaLista();

        raFT.textProperty().bindBidirectional(ac.raProperty());
        nomeTF.textProperty().bindBidirectional(ac.nomeProperty());
        idadeTF.textProperty().bindBidirectional(ac.idadeProperty());
        //

        // conecoes dos botoes com o alunoCOntrol
        inserir.setOnAction(event -> {
            ac.nascProperty().set(LocalDate.parse(nascimentoTF.getText()));
            ac.Inserir();
            ac.atualizaLista();
            ac.limparCampos();
            nascimentoTF.setText("");
        });

        atualizar.setOnAction(event -> {
            ac.nascProperty().set(LocalDate.parse(nascimentoTF.getText()));

            ac.Atualizar();
            ac.atualizaLista();
            ac.limparCampos();
            nascimentoTF.setText("");

        });

        remover.setOnAction(event -> {
            ac.Remover();
            ac.atualizaLista();
            ac.limparCampos();
            nascimentoTF.setText("");

        });

        pesquisar.setOnAction(event -> {
            ac.Pesquisar();
            ac.atualizaLista();
            nascimentoTF.setText(ac.nascProperty().get().toString());
        });

        painel.getChildren().addAll(entradas, cadastros);

        Scene cena = new Scene(painel, 500, 500);

        stage.setScene(cena);
        stage.show();

    }

}
