/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso.fatec;

import edu.curso.fatec.boundary.AlunoBoundary;
import javafx.application.Application;

public class App {

    public static void main(String[] args) {
        Application.launch(AlunoBoundary.class, args);

    }
}
